# Copyright (c) 2024 Dell Inc., or its subsidiaries. All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#  http://www.apache.org/licenses/LICENSE-2.0

# This workflow is used to release libraries like gobrick, gofsutil etc.
name: Release Go Client Libraries

# Invocable as a reusable workflow
on:
  workflow_call:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version to release (major, minor, patch), ex: 1.0.0'
        required: true
        type: string      
jobs:
  build-and-scan:    
    name: Build, Scan and Release
    runs-on: ubuntu-latest    
    steps:
      - name: Validate version input
        run: |
          if [[ "${{ github.event.inputs.version }}" == "none" ]]; then
            echo "Invalid version specified: ${{ github.event.inputs.version }} Must follow major, minor, patch versioning."
            exit 1
          fi
      - name: Checkout the code
        uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.23"
      - name: Install dependencies
        run: go mod tidy
      - name: Build
        run: go build -v ./...
      - name: Run malware scan
        uses: dell/common-github-actions/malware-scanner@main
        with:
          directories: .
          options: -ri
      - name : Create Tag and Release
        uses: harishp8889/test-common-github-actions/.github/workflows/tag-creator.yaml@main
        with:
          inputs: ${{ inputs.version}}
